# Generated by Django 4.2.7 on 2025-03-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_item_soundcloud_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='soundcloud_url',
        ),
        migrations.AddField(
            model_name='item',
            name='soundcloud_src',
            field=models.TextField(blank=True, default=''),
        ),
    ]
